[package]
name = "doorbell-zigbee"
version = "0.1.0"
authors = ["Dylan Stewart <jdylanstewart@gmail.com>"]
edition = "2021"
license = "MIT OR Apache-2.0"

[dependencies]
esp-idf-sys = "0.37"
esp-idf-hal = "0.46"
esp-idf-svc = "0.52"
log = "0.4"

[build-dependencies]
embuild = "0.33"

[profile.release]
opt-level = "s"
lto = true

[profile.dev]
opt-level = "s"
lto = true

[package.metadata.esp-idf-sys]
esp_idf_component_manager = "y"
esp_idf_partition_table_file = "partitions.csv"

[[package.metadata.esp-idf-sys.extra_components]]
remote_component = { name = "espressif/esp-zboss-lib", version = "~1.6.0" }

[[package.metadata.esp-idf-sys.extra_components]]
remote_component = { name = "espressif/esp-zigbee-lib", version = "~1.6.0" }
bindings_header = "src/zigbee_bindings.h"
bindings_module = "zigbee"
