[target.riscv32imc-unknown-none-elf]
runner = "espflash flash --monitor"
rustflags = ["-C", "link-arg=-Tlinkall.x"]

[build]
target = "riscv32imc-unknown-none-elf"

[unstable]
build-std = ["alloc", "core"]

[env]
ESP_LOG = "info"
WIFI_SSID = "5962 S Tempe Way"
WIFI_PASS = "kbds5962"
CURRENT_TIME_MS = "1723070000000"
CC = "/opt/homebrew/opt/llvm/bin/clang"
CXX = "/opt/homebrew/opt/llvm/bin/clang++"
